/* ============================================================
   ADCB Open Finance — Content Data
   Edit these arrays to update step content without touching layout.
   ============================================================ */

var DATA_STEPS = [
  { color: '#185FA5', label: 'You open a TPP app', detail: 'You launch a budgeting app or financial tool. It wants to read your ADCB transaction history. UAE law requires your explicit consent before any data can be shared \u2014 the app cannot access it without your approval.', pills: ['Customer', 'TPP App', 'CBUAE consent law'] },
  { color: '#3B6D11', label: 'TPP creates a consent request', detail: 'The TPP calls POST /account-access-consents on the API Hub, listing which data clusters it needs \u2014 e.g. Transactions, Balances, Account Details. Nothing is shared yet. The Hub returns a consent ID and a redirect URL.', pills: ['POST /account-access-consents', 'API Hub', 'Consent ID'] },
  { color: '#854F0B', label: 'API Hub redirects you to your bank', detail: 'The TPP redirects you to your bank\'s login page. This is OAuth 2.0 at work \u2014 the TPP never sees your password. The entire auth flow is brokered by the Hub using FAPI 2.0 security and mutual TLS certificates.', pills: ['OAuth 2.0', 'FAPI 2.0', 'mTLS', 'Redirect'] },
  { color: '#0F6E56', label: 'You authenticate and approve at your bank', detail: 'You log in to ADCB and see a clear consent screen listing exactly what the TPP is requesting. You approve using SCA \u2014 Strong Customer Authentication (biometric or OTP). Your bank records the consent.', pills: ['LFI (ADCB)', 'SCA', 'Consent screen', 'CX Certified'] },
  { color: '#854F0B', label: 'API Hub issues access tokens to the TPP', detail: 'After you approve, the Hub issues an access token and refresh token to the TPP. These are time-limited credentials \u2014 not your password. The TPP stores them securely for future API calls within the consent window (up to 365 days).', pills: ['Access token', 'Refresh token', 'Time-limited', 'API Hub'] },
  { color: '#3B6D11', label: 'TPP calls the data APIs', detail: 'The TPP calls GET /accounts, GET /accounts/{id}/transactions, etc. Each call includes the Bearer token. The Hub validates it and routes the request to ADCB via Ozone Connect. Nebras charges 2.5 fils per 100 lines of transaction data.', pills: ['GET /accounts', 'GET /transactions', 'Bearer Token', 'Ozone Connect'] },
  { color: '#185FA5', label: 'Your data appears in the TPP app', detail: 'Your transaction data flows back: LFI \u2192 API Hub \u2192 TPP \u2192 displayed in the app. You can revoke consent at any time via DELETE /account-access-consents/{id} and the TPP must stop accessing your data immediately.', pills: ['Data response', 'Revocable consent', 'DELETE /account-access-consents/{id}'] }
];

var SIP_STEPS = [
  { color: '#185FA5', label: 'You initiate a payment in a TPP app', detail: 'You tap "Pay" in a merchant checkout or P2P transfer screen. You enter the amount (AED only, minimum 0.01 AED) and recipient details. The TPP prepares the payment request.', pills: ['Customer', 'TPP App', 'AED only', 'IPP rail'] },
  { color: '#3B6D11', label: 'TPP runs Confirmation of Payee (CoP)', detail: 'Before creating a payment consent, the TPP calls POST /customers/action/cop-query. The Hub verifies the recipient\'s name matches their bank account. This protects you from APP fraud \u2014 sending money to the wrong or impersonated account.', pills: ['POST /cop-query', 'Name verification', 'Fraud prevention', 'CoP'] },
  { color: '#3B6D11', label: 'TPP creates a payment consent', detail: 'The TPP calls POST /payment-consents with payment details: amount, recipient IBAN, reference, and a mandatory Risk Information Block (Customer Present flag, Initiating Channel, merchant details). This consent is single-use only.', pills: ['POST /payment-consents', 'Risk Information Block', 'Single-use', 'API Hub'] },
  { color: '#854F0B', label: 'API Hub redirects you to your bank', detail: 'You are redirected to ADCB to authorise this specific payment. The Hub sends the full payment details ahead: amount, recipient name, account, reference. Your bank shows you exactly what you are authorising \u2014 not a generic approval.', pills: ['OAuth 2.0', 'FAPI 2.0', 'Payment details redirect'] },
  { color: '#0F6E56', label: 'You authenticate and approve the payment', detail: 'You confirm with SCA (biometric or OTP). Your bank authorises the payment consent. Important: the money has NOT moved yet. Authorisation is permission \u2014 execution is the next step.', pills: ['LFI (ADCB)', 'SCA', 'Consent authorised', 'Money not moved yet'] },
  { color: '#854F0B', label: 'API Hub confirms authorisation to the TPP', detail: 'The Hub returns the authorisation code and payment consent ID to the TPP. The TPP now holds a one-time credential to submit the actual payment. This also unlocks the access token.', pills: ['Auth code', 'Payment consent ID', 'API Hub'] },
  { color: '#3B6D11', label: 'TPP submits the payment', detail: 'The TPP calls POST /domestic-payments using the authorised consent ID. The Hub routes this to ADCB via Ozone Connect. ADCB submits to the IPP (Instant Payment Platform) rail. Nebras charges 2.5 fils. The payment is now in-flight.', pills: ['POST /domestic-payments', 'IPP rail', 'Ozone Connect', '2.5 fils fee'] },
  { color: '#185FA5', label: 'Payment executes and status updates', detail: 'The IPP processes the payment in real-time. Status transitions: PDNG (received) \u2192 ACSC (your account debited) \u2192 ACCC (recipient credited and confirmed). The TPP polls GET /domestic-payments/{paymentId} to track progress.', pills: ['PDNG \u2192 ACSC \u2192 ACCC', 'IPP real-time', 'GET /domestic-payments/{id}'] }
];

var STATUS_INFO = {
  pending: 'PDNG \u2014 Pending: The bank received the payment instruction and submitted it to the IPP rail. The money has not moved yet \u2014 it is queued for processing. The TPP polls until this changes.',
  rejected: 'RJCT \u2014 Rejected: The payment was refused before execution. Common reasons: insufficient funds, AML/compliance flag, invalid recipient details, or the bank\'s own risk controls. The TPP is notified via the status endpoint.',
  acsc: 'ACSC \u2014 Accepted Settlement Completed (Debtor): YOUR account at ADCB has been debited. The money has left your account and is in transit to the recipient\'s bank. The sending side is fully done.',
  accc: 'ACCC \u2014 Accepted Credit Settlement Completed: The recipient\'s bank confirmed the credit to their account. The payment is fully complete \u2014 both sides have settled. This is the final success state.',
  acwp: 'ACWP \u2014 Accepted Without Posting: The recipient\'s bank accepted the payment but has not yet posted it to the account (e.g. queued for end-of-day batch). A rare intermediate state seen in certain LFI configurations.'
};
